import { formatINR, formatDateTime, formatPercent } from './format';

const NAVY = [27, 42, 74];
const INK = [22, 35, 61];
const INK_SOFT = [76, 90, 112];
const EMERALD = [31, 111, 84];
const GOLD_TINT = [246, 236, 216];
const BORDER = [221, 216, 200];

/**
 * Renders a single saved calculation as a clean one-page PDF summary,
 * hand-drawn with jsPDF primitives to match the app's ledger-receipt look.
 * jsPDF is loaded on demand so it doesn't bloat the initial page bundle.
 */
export async function generateCalculationPdf(calc) {
  const { jsPDF } = await import('jspdf');
  const doc = new jsPDF({ unit: 'pt', format: 'a4' });
  const pageWidth = doc.internal.pageSize.getWidth();
  const marginX = 48;
  const rightX = pageWidth - marginX;
  let y = 0;

  // ---- Header band ----
  doc.setFillColor(...NAVY);
  doc.rect(0, 0, pageWidth, 96, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(20);
  doc.text('TaxWise', marginX, 42);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(11);
  doc.text('Income Tax Calculation Summary', marginX, 62);
  doc.setFontSize(8.5);
  doc.text(`Generated ${formatDateTime(new Date())}`, marginX, 80);

  const regimeText = calc.regime === 'NEW' ? 'New Regime' : 'Old Regime';

  y = 132;
  doc.setTextColor(...INK);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(15);
  doc.text(calc.label || `FY ${calc.financialYear} \u2014 ${regimeText}`, marginX, y);

  y += 18;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9.5);
  doc.setTextColor(...INK_SOFT);
  const metaLine = [
    `Financial Year ${calc.financialYear}`,
    regimeText,
    calc.createdAt ? `Saved ${formatDateTime(calc.createdAt)}` : null,
  ]
    .filter(Boolean)
    .join('   \u00b7   ');
  doc.text(metaLine, marginX, y);

  y += 26;

  function sectionTitle(title) {
    doc.setFillColor(...GOLD_TINT);
    doc.rect(marginX, y - 12, rightX - marginX, 20, 'F');
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(9.5);
    doc.setTextColor(...INK);
    doc.text(title.toUpperCase(), marginX + 8, y + 2);
    y += 26;
  }

  function row(label, value, { bold = false, indent = 0 } = {}) {
    doc.setFont('helvetica', bold ? 'bold' : 'normal');
    doc.setFontSize(10);
    doc.setTextColor(...(bold ? INK : INK_SOFT));
    doc.text(label, marginX + indent, y);
    doc.setFont('courier', bold ? 'bold' : 'normal');
    doc.setTextColor(...INK);
    doc.text(value, rightX, y, { align: 'right' });
    y += 17;
  }

  function divider() {
    doc.setDrawColor(...BORDER);
    doc.setLineWidth(0.75);
    doc.line(marginX, y - 6, rightX, y - 6);
    y += 6;
  }

  sectionTitle('Income & Deductions');
  row('Gross annual income', formatINR(calc.grossIncome), { bold: true });
  row('Standard deduction', `- ${formatINR(calc.standardDeduction)}`);
  if (Number(calc.hraExemption) > 0) {
    row('HRA exemption', `- ${formatINR(calc.hraExemption)}`);
  }
  row('Total deductions', `- ${formatINR(calc.totalDeductions)}`);
  divider();
  row('Taxable income', formatINR(calc.taxableIncome), { bold: true });

  y += 10;
  sectionTitle('Tax Computation');
  row('Tax before cess', formatINR(calc.taxBeforeCess));
  if (Number(calc.rebate87A) > 0) {
    row('Rebate under Section 87A', `- ${formatINR(calc.rebate87A)}`);
  }
  if (Number(calc.surcharge) > 0) {
    row('Surcharge', formatINR(calc.surcharge));
  }
  row('Health & education cess (4%)', formatINR(calc.cess));
  divider();
  row('Total tax liability', formatINR(calc.totalTaxLiability), { bold: true });
  row('Effective tax rate', formatPercent(calc.effectiveTaxRatePercent));

  y += 10;
  sectionTitle('Take-home');
  row('Net take-home (annual)', formatINR(calc.netTakeHomeAnnual), { bold: true });
  row('Net take-home (monthly)', formatINR(calc.netTakeHomeMonthly));

  if (calc.comparisonRegimeTax !== undefined && calc.comparisonRegimeTax !== null) {
    y += 10;
    sectionTitle('Regime Comparison');
    const otherLabel = calc.comparisonRegime === 'NEW' ? 'New Regime' : 'Old Regime';
    row(`${otherLabel} total tax`, formatINR(calc.comparisonRegimeTax));
    if (calc.potentialSavings !== undefined) {
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(10);
      doc.setTextColor(...EMERALD);
      doc.text(
        `${calc.betterRegime === calc.regime ? 'This regime' : otherLabel} saves ${formatINR(calc.potentialSavings)} vs. the alternative`,
        marginX,
        y
      );
      y += 17;
    }
  }

  // ---- Footer ----
  const pageHeight = doc.internal.pageSize.getHeight();
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.setTextColor(...INK_SOFT);
  doc.text(
    'This is an estimate generated by TaxWise for planning purposes only. It is not a substitute for advice from a',
    marginX,
    pageHeight - 40
  );
  doc.text('qualified chartered accountant or a return filed with the Income Tax Department.', marginX, pageHeight - 30);

  const fileSafeLabel = (calc.label || `taxwise-${calc.financialYear}-${calc.regime}`)
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/(^-|-$)/g, '');
  doc.save(`${fileSafeLabel || 'taxwise-summary'}.pdf`);
}
